;; Copyright (C) 2026 Matt Hargett. All rights reserved.
;; SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

(component
  (type $host-interface
    (instance
      (export "item" (type (sub resource)))
      (export "item-alias-00" (type (eq 0)))
      (export "item-alias-01" (type (eq 0)))
      (export "item-alias-02" (type (eq 0)))
      (export "item-alias-03" (type (eq 0)))
      (export "item-alias-04" (type (eq 0)))
      (export "item-alias-05" (type (eq 0)))
      (export "item-alias-06" (type (eq 0)))
      (export "item-alias-07" (type (eq 0)))
      (export "item-alias-08" (type (eq 0)))
      (export "item-alias-09" (type (eq 0)))
      (export "item-alias-10" (type (eq 0)))
      (export "item-alias-11" (type (eq 0)))
      (export "item-alias-12" (type (eq 0)))
      (export "item-alias-13" (type (eq 0)))
      (export "item-alias-14" (type (eq 0)))
      (export "item-alias-15" (type (eq 0)))
      (export "item-alias-16" (type (eq 0)))
      (export "item-alias-17" (type (eq 0)))
      (export "item-alias-18" (type (eq 0)))
      (export "item-alias-19" (type (eq 0)))
      (export "item-alias-20" (type (eq 0)))
      (export "item-alias-21" (type (eq 0)))
      (export "item-alias-22" (type (eq 0)))
      (export "item-alias-23" (type (eq 0)))
      (export "item-alias-24" (type (eq 0)))
      (export "item-alias-25" (type (eq 0)))
      (export "item-alias-26" (type (eq 0)))
      (export "item-alias-27" (type (eq 0)))
      (export "item-alias-28" (type (eq 0)))
      (export "item-alias-29" (type (eq 0)))
      (export "item-alias-30" (type (eq 0)))
      (export "item-alias-31" (type (eq 0)))
      (export "item-alias-32" (type (eq 0)))
      (export "item-alias-33" (type (eq 0)))
      (export "item-alias-34" (type (eq 0)))
      (export "item-alias-35" (type (eq 0)))
      (export "item-alias-36" (type (eq 0)))
      (export "item-alias-37" (type (eq 0)))
      (export "item-alias-38" (type (eq 0)))
      (export "item-alias-39" (type (eq 0)))
      (export "item-alias-40" (type (eq 0)))
      (export "item-alias-41" (type (eq 0)))
      (export "item-alias-42" (type (eq 0)))
      (export "item-alias-43" (type (eq 0)))
      (export "item-alias-44" (type (eq 0)))
      (export "item-alias-45" (type (eq 0)))
      (export "item-alias-46" (type (eq 0)))
      (export "item-alias-47" (type (eq 0)))
      (export "item-alias-48" (type (eq 0)))
      (export "item-alias-49" (type (eq 0)))
      (export "item-alias-50" (type (eq 0)))
      (export "item-alias-51" (type (eq 0)))
      (export "item-alias-52" (type (eq 0)))
      (export "item-alias-53" (type (eq 0)))
      (export "item-alias-54" (type (eq 0)))
      (export "item-alias-55" (type (eq 0)))
      (export "item-alias-56" (type (eq 0)))
      (export "item-alias-57" (type (eq 0)))
      (export "item-alias-58" (type (eq 0)))
      (export "item-alias-59" (type (eq 0)))
      (export "item-alias-60" (type (eq 0)))
      (export "item-alias-61" (type (eq 0)))
      (export "item-alias-62" (type (eq 0)))
      (export "item-alias-63" (type (eq 0)))
      (type $ping-type (func))
      (export "ping" (func (type $ping-type)))))

  (import "test:alias/large@1.0.0"
    (instance (type $host-interface))))
