/*
 * Copyright (C) 2026 Airbus Defence and Space Romania SRL. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

#ifndef WASM_COMPONENT_HOST_RESOURCE_H
#define WASM_COMPONENT_HOST_RESOURCE_H

#include <stdint.h>
#include <stdbool.h>
#include "bh_hashmap.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum HostResourceType {
    WASI_P2_ERROR = 1,                         // error
    WASI_P2_IO_INPUT_STREAM = 2,               // input-stream
    WASI_P2_IO_OUTPUT_STREAM = 3,              // output-stream
    WASI_P2_DIRECTORY_ENTRY_STREAM = 4,        // directory-entry-stream
    WASI_P2_FILESYSTEM_DESCRIPTOR = 5,         // descriptor
    WASI_P2_TERMINAL_OUTPUT = 6,               // terminal-output
    WASI_P2_TERMINAL_INPUT = 7,                // terminal-input
    WASI_P2_TCP_SOCKET = 8,                    // tcp-socket
    WASI_P2_UDP_SOCKET = 9,                    // udp-socket
    WASI_P2_NETWORK = 10,                      // network
    WASI_P2_UDP_INCOMING_DATAGRAM_STREAM = 11, // incoming-stream
    WASI_P2_UDP_OUTGOING_DATAGRAM_STREAM = 12, // outgoing-stream
    WASI_P2_POLLABLE = 13,                     // pollable
    WASI_P2_RESOLVE_ADDRESS_STREAM = 14,       // resolve-address-stream
} HostResourceType;

typedef enum IOStreamType {
    STREAM_TYPE_SOCKET = 1,  // generated by sockets:tcp
    STREAM_TYPE_FILE = 2,    // generated by filesystem:desriptor
    STREAM_TYPE_GENERIC = 3, // generated by cli:stdout / cli:stdin / cli:stderr
    STREAM_TYPE_HOST_CALLBACK = 4
} IOStreamType;

typedef struct StreamResourceType {
    IOStreamType type;
    uint32_t fd;
    /* File streams use positional I/O so dup() never shares or mutates the
       descriptor resource's kernel cursor/append flags. */
    uint64_t position;
    bool position_valid;
    bool append;
} StreamResourceType;

typedef void (*host_resource_dtor_t)(void *data);
typedef void (*host_resource_native_fd_release_t)(void *attachment,
                                                  uint32_t fd_count);

typedef struct HostResource {
    void *data;
    HostResourceType type;
    host_resource_dtor_t dtor;
    void *native_fd_quota_attachment;
    host_resource_native_fd_release_t native_fd_quota_release;
    uint32_t native_fd_quota_count;
    uint32_t pin_count;
    bool registered;
    bool closing;
    struct HostResource *deferred_next;
} HostResource;

typedef HashMap HostResourceTable;

/*
 * Host resource borrows are scoped to one synchronous native call.  The
 * actual pin records live in fixed thread-local storage so a guest trap or
 * thread exit can unwind them without dereferencing an abandoned C stack
 * frame.  This caller-owned value is only an opaque normal-return token.
 */
#define HOST_RESOURCE_PIN_SCOPE_CAPACITY 32
#define HOST_RESOURCE_PIN_SCOPE_MAX_DEPTH 16

typedef struct HostResourcePinScope {
    uint64_t cookie;
    uint32_t depth;
    bool active;
} HostResourcePinScope;

extern HostResourceTable *g_host_resource_table;

bool
instantiate_host_resource_table();
HostResourceTable *
get_global_host_resource_table();
void
destroy_host_resource_table();

bool
host_resource_pin_scope_enter(HostResourcePinScope *scope);
bool
host_resource_pin_scope_enter_for_unwind_target(HostResourcePinScope *scope,
                                                const void *unwind_target);
void
host_resource_pin_scope_leave(HostResourcePinScope *scope);
/* Release scopes abandoned by a nonlocal exit to the given runtime jmpbuf. */
void
host_resource_pin_scope_unwind_to(const void *unwind_target);
/* Release every scope before a guest thread exits without returning. */
void
host_resource_pin_scope_unwind_current(void);

uint32_t
host_resource_table_add(HostResourceTable *table, HostResource *hr);
HostResource *
host_resource_table_get(HostResourceTable *table, uint32_t id);
uint32_t
host_resource_table_delete(HostResourceTable *table, uint32_t id);
uint32_t
host_resource_table_get_next_id(HostResourceType type);

#if defined(WAMR_HOST_RESOURCE_ID_TESTING)
uint32_t
host_resource_table_set_next_id_for_test(uint32_t next_id);
#endif

// Helpers
HostResource *
host_resource_create(HostResourceType type, uint32_t data_size);

void
host_resource_set_dtor(HostResource *hr, host_resource_dtor_t dtor);

void
host_resource_set_native_fd_quota(
    HostResource *hr, void *attachment,
    host_resource_native_fd_release_t release_callback, uint32_t fd_count);

void
destroy_host_resource(HostResource *hr);

#ifdef __cplusplus
}
#endif

#endif
